# Generated by Django 5.1.5 on 2025-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_app', '0002_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='icon',
        ),
        migrations.AddField(
            model_name='update',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
